version: '2'
services:
  webapp_setup:
    build: .
    depends_on:
      - postgres
    command: bundle exec puma -C config/puma.rb
  webapp:
    container_name: webapp
    build: .
    depends_on:
      - postgres
      - webapp_setup
    volumes:
      - /home/vzl/work/docker/rordocker2/webapp
    ports:
      - "3000:3000"
  web:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    links:
      - webapp
    ports:
      - "80:80"
  postgres:
    image: postgres:9.5.3
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=webapp
      - POSTGRES_DB=webapp_development
    volumes_from:
      - postgres_data
  postgres_data:
      image: postgres:9.5.3
      volumes:
        - /var/lib/postgresql/data
      command: /bin/true
